### ISSUE TITLE
Test workflow not triggering on push

### ISSUE THREAD

**Issue by allddd** [allddd/headscale-apt#1]
Changes to the repository made through the `realease.yml` workflow do not trigger the `test.yml`, even though the following is configured:

```yml
[...]
on:
  push:
    branches:
      - main
    paths:
      - VERSION
[...]
```

The problem seems to be that the realease workflow pushes changes using `GITHUB_TOKEN`, which [prevents it from triggering another workflow](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/triggering-a-workflow#triggering-a-workflow-from-a-workflow).

A possible workaround is to provide an actual personal access token to `actions/checkout`.
